
## Role id 
ROLE_ADMIN  = 0
ROLE_STAFF  = 1
ROLE_LEAD   = 2
ROLE_MEMBER = 3

## Reservation type
RESV_TYPE_REQ_QUIET     = 1
RESV_TYPE_NOISY         = 2
RESV_TYPE_NOT_REQ_QUIET = 3

## Column Father ID
COLUMN_HOME = 0
COLUMN_USERS = 1
COLUMN_STATISTICS = 2
COLUMN_RESERVATION = 3
COLUMN_TEAMS = 4
COLUMN_TRAINING = 5