# Generated by Django 3.2.12 on 2022-03-14 20:58

from django.db import migrations
from reservation.models import *
import os

def init(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    #Zone = apps.get_model('reservation', 'Zone')
    Zone.objects.create(id = 1, name = "Office", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 2, name = "Conference Table", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 3, name = "Machine Shop", is_noisy = True, description = "", zone_type = 1)
    Zone.objects.create(id = 4, name = "Work Table 1", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 5, name = "Work Table 2", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 6, name = "Work Table 3", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 7, name = "Work Table 4", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 8, name = "Work Table 5", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 9, name = "Work Table 6", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 10, name = "Work Table 7", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 11, name = "Work Table 8", is_noisy = False, description = "", zone_type = 1)
    
    #Role = apps.get_model('reservation', 'Role')
    role_admin = Role.objects.create(id = 0, role_name = "admin")
    role_staff = Role.objects.create(id = 1, role_name = "staff")
    role_team_leader = Role.objects.create(id = 2, role_name = "team leader")
    role_member = Role.objects.create(id = 3, role_name = "member")
    
    # Test data
    # Default admin
    SHARED_SPACE_ADMIN_PASSWORD = os.environ['SHARED_SPACE_ADMIN_PASSWORD']
    superuser = User(username = 'admin', email = 'admin@admin.net', is_active = True, is_superuser = True, is_staff = True, role_id = role_admin)
    superuser.set_password(SHARED_SPACE_ADMIN_PASSWORD)
    superuser.save()
    
    test_member_1 = User(username = 'test_member_1', email = 'test_member_1@tamu.edu', is_active = True, is_superuser = True, is_staff = True, role_id = role_member)
    test_member_1.set_password('123')
    test_member_1.save()
    
    test_member_2 = User(username = 'test_member_2', email = 'test_member_2@tamu.edu', is_active = True, is_superuser = True, is_staff = True, role_id = role_member)
    test_member_2.set_password('123')
    test_member_2.save()
    
    #UserModel = apps.get_model('reservation', 'User')
    User.objects.create(username = "test_admin_1", email = "test_admin_1@tamu.edu", role_id = role_admin)
    User.objects.create(username = "test_admin_2", email = "test_admin_2@tamu.edu", role_id = role_admin)
    User.objects.create(username = "test_staff_1", email = "test_staff_1@tamu.edu", role_id = role_staff)
    User.objects.create(username = "test_staff_2", email = "test_staff_2@tamu.edu", role_id = role_staff)
    #User.objects.create(id = 3, username = "test_lead_1", email = "test_lead_1@tamu.edu", role_id = 2)
    #User.objects.create(id = 3, username = "test_lead_2", email = "test_lead_2@tamu.edu", role_id = 2)
    #user5 = UserModel.objects.create(username = "test_member_1", email = "test_member_1@tamu.edu", role_id = 2)
    test_member_1 = User.objects.get(username = "test_member_1")
    test_member_2 = User.objects.get(username = "test_member_2")
    test_member_3 = User.objects.create(username = "test_member_3", email = "test_member_3@tamu.edu", role_id = role_member)
    User.objects.create(username = "test_member_4", email = "test_member_4@tamu.edu", role_id = role_member)
    User.objects.create(username = "test_member_5", email = "test_member_5@tamu.edu", role_id = role_member)


   # Team = apps.get_model('reservation', 'Team')
    team1 = Team.objects.create(name = "test_team_1", leader_id = test_member_1)
    Team.objects.create(name = "test_team_2")
    
    #TeamMember = apps.get_model('reservation', 'TeamMember')
    TeamMember.objects.create(team_id = team1, user_id = test_member_1)
    TeamMember.objects.create(team_id = team1, user_id = test_member_2)
    TeamMember.objects.create(team_id = team1, user_id = test_member_3)
    
    
    from django.contrib.sites.models import Site
    from allauth.socialaccount.models import SocialApp, SocialAccount
    
    SHARED_SPACE_GOOGLE_CLIENT_ID = os.environ['SHARED_SPACE_GOOGLE_CLIENT_ID']
    SHARED_SPACE_GOOGLE_SECRET = os.environ['SHARED_SPACE_GOOGLE_SECRET']
    
    social_app = SocialApp.objects.create(provider = 'google', name = 'sharedspace', 
        client_id = SHARED_SPACE_GOOGLE_CLIENT_ID,
        secret = SHARED_SPACE_GOOGLE_SECRET)
    
    site = Site.objects.create(domain='sharedspace.com', name='sharedspace.com')
    social_app.sites.add(site) # set site 
            
        


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
        ('socialaccount', '0003_extra_data_default_dict'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(init)
    ]

