# Generated by Django 3.2.12 on 2022-03-14 20:58

from django.db import migrations
from reservation.models import *
import os

def init(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    #Zone = apps.get_model('reservation', 'Zone')
    Zone.objects.create(id = 1, name = "Office", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 2, name = "Conference Table", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 3, name = "Machine Shop", is_noisy = True, description = "", zone_type = 1)
    Zone.objects.create(id = 4, name = "Work Table 1", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 5, name = "Work Table 2", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 6, name = "Work Table 3", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 7, name = "Work Table 4", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 8, name = "Work Table 5", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 9, name = "Work Table 6", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 10, name = "Work Table 7", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 11, name = "Work Table 8", is_noisy = False, description = "", zone_type = 1)
    
    #Role = apps.get_model('reservation', 'Role')
    role_admin = Role.objects.create(id = 0, role_name = "admin")
    role_staff = Role.objects.create(id = 1, role_name = "staff")
    role_team_leader = Role.objects.create(id = 2, role_name = "team leader")
    role_member = Role.objects.create(id = 3, role_name = "member")
    
    # Default admin
    SHARED_SPACE_ADMIN_PASSWORD = os.environ['SHARED_SPACE_ADMIN_PASSWORD']
    superuser = User(username = 'admin', email = 'admin@admin.net', is_active = True, is_superuser = True, is_staff = True, role_id = role_admin)
    superuser.set_password(SHARED_SPACE_ADMIN_PASSWORD)
    superuser.save()
    
    # Google auth config
    from django.contrib.sites.models import Site
    from allauth.socialaccount.models import SocialApp, SocialAccount
    
    SHARED_SPACE_GOOGLE_CLIENT_ID = os.environ['SHARED_SPACE_GOOGLE_CLIENT_ID']
    SHARED_SPACE_GOOGLE_SECRET = os.environ['SHARED_SPACE_GOOGLE_SECRET']
    
    social_app = SocialApp.objects.create(provider = 'google', name = 'sharedspace', 
        client_id = SHARED_SPACE_GOOGLE_CLIENT_ID,
        secret = SHARED_SPACE_GOOGLE_SECRET)
    
    site = Site.objects.create(domain='sharedspace.com', name='sharedspace.com')
    social_app.sites.add(site) # set site 
            
        
    #leftNav
    LeftNav.objects.create(id = 1, name = "Home", url = "index", fid=0, description = "")
    LeftNav.objects.create(id = 2, name = "Staff Management", url = "/usermng/staff", fid=1, description = "")
    LeftNav.objects.create(id = 3, name = "Authorization", url = "/usermng/authUser", fid=1, description = "")
    LeftNav.objects.create(id = 4, name = "Make Reservations", url = "index", fid=3, description = "")
    LeftNav.objects.create(id = 5, name = "Reservation History", url = "/reservation/history", fid=3, description = "")
    LeftNav.objects.create(id = 6, name = "Overall", url = "statOverall", fid=2, description = "")
    LeftNav.objects.create(id = 7, name = "Reserve Statistics", url = "statReserve", fid=2, description = "")
    LeftNav.objects.create(id = 8, name = "Training Statistics", url = "statTraining", fid=2, description = "")
    LeftNav.objects.create(id = 9, name = "Register Statistics", url = "statRegister", fid=2, description = "")
    LeftNav.objects.create(id = 10, name = "Team Management", url = "/team/view", fid=4, description = "")
    LeftNav.objects.create(id = 11, name = "My Teams", url = "/team/view", fid=4, description = "")
    LeftNav.objects.create(id = 12, name = "Training Management", url = "/training/view", fid=5, description = "")
    LeftNav.objects.create(id = 13, name = "Registered Training", url = "/training/apply/myTrainning", fid=5, description = "")
    LeftNav.objects.create(id = 14, name = "Training Registration", url = "/training/apply", fid=5, description = "")

class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
        ('socialaccount', '0003_extra_data_default_dict'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(init)
    ]

