# Generated by Django 3.2.12 on 2022-03-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='is_long_term',
        ),
        migrations.AddField(
            model_name='reservation',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='title',
            field=models.CharField(default='untitled', max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_type',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='team_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='zone_id',
            field=models.IntegerField(default=0),
        ),
    ]
