# Generated by Django 3.2.12 on 2022-03-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20220312_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_long_term',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_type',
            field=models.IntegerField(),
        ),
    ]
