# Generated by Django 3.2.12 on 2022-03-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20220313_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='name',
            field=models.CharField(default='noname', max_length=50),
        ),
        migrations.AlterField(
            model_name='zone',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='zone',
            name='is_noisy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone_type',
            field=models.IntegerField(default=1),
        ),
    ]
