# Generated by Django 3.2.12 on 2022-03-14 02:44

from django.db import migrations


def init(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Zone = apps.get_model('reservation', 'Zone')
    Zone.objects.create(id = 1, name = "Office", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 2, name = "Conference Table", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 3, name = "Machine Shop", is_noisy = True, description = "", zone_type = 1)
    Zone.objects.create(id = 4, name = "Work Table 1", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 5, name = "Work Table 2", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 6, name = "Work Table 3", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 7, name = "Work Table 4", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 8, name = "Work Table 5", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 9, name = "Work Table 6", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 10, name = "Work Table 7", is_noisy = False, description = "", zone_type = 1)
    Zone.objects.create(id = 11, name = "Work Table 8", is_noisy = False, description = "", zone_type = 1)


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20220313_1828'),
    ]

    operations = [
        migrations.RunPython(init)
    ]
