# Generated by Django 3.2.12 on 2022-03-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20220313_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='zone_name',
            field=models.CharField(default='noname', max_length=50),
        ),
    ]
